name: green_saudi_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter_svg: ^2.0.10+1
  get_storage:
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.3.4
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  flutter_otp_text_field: ^1.1.3+2
  timer_count_down: ^2.2.2
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.6

  image_picker: ^1.0.8
  flutter_localization: ^0.2.0
  translator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/icons/
